name: Check for Latest Articles

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4:00 UTC (10 pm MT) every day-of-week
    - cron: '0 18 * * *'  # Runs at 18:00 UTC (12 pm MT) every day-of-week

  repository_dispatch:
    types:
      - webhook_check_for_latest_articles

jobs:
  update_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv feedparser chromadb langchain openai

      - name: Run data.py
        id: script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STRATECHERY_RSS_ID: ${{ secrets.STRATECHERY_RSS_ID }}
          STRATECHERY_ACCESS_TOKEN: ${{ secrets.STRATECHERY_ACCESS_TOKEN }}
        run: |
          python3 data.py
        shell: bash

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Commit and push changes if changes exist
        if: steps.changes.outputs.changes_exist == 'true'
        run: |
          git config --global user.email "gordon.weakliem@gmail.com"
          git config --global user.name "Gordon Weakliem"
          git add .
          git commit -m "Auto-add new article(s)"
          git push
